[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
VITE_SUPABASE_URL = "https://dowapvpytpzhhqdtycia.supabase.co"
VITE_SUPABASE_PUBLISHABLE_KEY = "sb_publishable_Co0hw2sGrlp9SV2J8_xZqw_xpnViq9r"
