import { Experience } from "@_types";

export const experience: Experience[] = [
  {
    id: 1,
    position: "Frontend Developer",
    place: "PTT Digital Solutions Company Limited",
    start_date: "2026-01-01",
    end_date: null,
    work: [
      "Develop and maintain web applications using Next.js, React.js, and modern JavaScript (ES6+)",
      "Build scalable modules for POS systems (transaction flows, receipts, payment integrations), inventory management (stock tracking, reporting, analytics dashboards), backoffice admin panels (role-based access, reporting systems), and carpool service platforms (booking flows, trip management)",
      "Implement responsive UI using Tailwind CSS / CSS Modules / Styled Components",
      "Optimize applications for performance, SEO, and accessibility",
      "Integrate RESTful APIs and third-party services",
      "Manage state using Redux / Context API / Zustand",
      "Implement authentication & authorization (JWT, OAuth)",
      "Collaborate with backend and product teams to deliver scalable solutions",
      "Write clean, maintainable, and reusable code and perform code reviews",
    ],
  },
  {
    id: 2,
    position: "React Developer",
    place: "100x",
    start_date: "2024-06-01",
    end_date: "2025-04-01",
    work: [
      "Develop and maintain high-performance web interfaces for core Web3 products using React.js and TypeScript",
      "Build scalable frontend modules for perpetual trading platform (DESK) including order books, trading UI, dashboards, analytics screens, real-time price feeds, and chart components",
      "Develop Telegram mini app integrations (Reward/points UI, trading funnels)",
      "Implement responsive and accessible UI components using Tailwind CSS, CSS Modules, or modern styling systems",
      "Integrate with blockchain-enabled APIs, WebSocket feeds, and decentralized infrastructure",
      "Work with authentication flows (wallet connect, OAuth, JWT)",
      "Optimize applications for performance, cross-device compatibility, and user experience",
      "Collaborate with UX/UI designers, product managers, and blockchain developers within Scrum/Agile framework",
      "Participate in sprint planning, daily stand-ups, backlog refinement, sprint reviews, and retrospectives",
      "Contribute to code reviews, maintain clean architecture, and improve development workflows",
    ],
  },
  {
    id: 3,
    position: "Graphic Designer",
    place: "Sabuy Technology Co.,ltd - Sabuy Digital",
    start_date: "2022-09-01",
    end_date: "2022-12-01",
    work: [
      "Taking part as an Exhibitor: Thailand Crypto Expo, Blockchain Genesis Thailand, Digitect Asean",
      "Content Creating: for Advertising Campaigns",
      "Graphic Desiging: 3D, Artwork, Announcement",
      "VDO Editing: for Exhibitions",
      "Gamification Design: for User Experience",
    ],
  },
  {
    id: 4,
    position: "Intern",
    place: "Auros Company Limited - Land Analysis and Development Consultant",
    start_date: "2021-06-01",
    end_date: "2021-08-01",
    work: [
      "Database Building - Update property listings: Location, Market Price, Land Size",
      "Land Survey - across Bangkok",
      "Comparative Research Analysis",
      "Document Interpretation (TH to ENG)",
    ],
  },
];
